spring:

  profiles:
    active: development

  datasource:
    url: jdbc:h2:mem:TemporaryDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: admin
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    enabled: false

  main:
    allow-bean-definition-overriding: true

    