spring:

  profiles:
    active: development

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  flyway:
    enabled: true

  main:
    allow-bean-definition-overriding: true
