spring:

  profiles:
    active: development

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  sql:
    init:
      mode: never

  flyway:
    enabled: false

  main:
    allow-bean-definition-overriding: true
